import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/context/AuthContext";
import Navigation from "@/components/Navigation";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-lightGray h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <main className="flex h-full relative">
            
            <Navigation />
            <div className="flex-1 md:ml-64 bg-gradient-to-r from-green-200 via-emerald-300 to-teal-400 px-4 md:px-8 lg:px-12 overflow-y-auto">
              <Header/>
              {children}
            </div>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
